/* Login & Register */
export const SET_REGISTER = 'SET_REGISTER';
export const SET_LOGIN = 'SET_LOGIN';

/* Modal/Alert */
export const SET_MODAL_SUCCESS_REGISTER = 'SET_MODAL_SUCCESS_REGISTER';
export const SET_MODAL_SUCCESS_LOGIN = 'SET_MODAL_SUCCESS_LOGIN';
export const SET_MODAL_ERROR_REGISTER = 'SET_MODAL_ERROR_REGISTER';
export const SET_MODAL_ERROR_LOGIN = 'SET_MODAL_ERROR_LOGIN';

/* TODOS */
export const SET_ALL_TODOS = 'SET_ALL_TODOS';

/* ITEMS */
export const SET_ALL_ITEMS = 'SET_ALL_ITEMS';
